<?php 
	$texts = array(
		//Barra Navegación superior y login
		'Idioma'=>'Language',
		'Español'=>'Spanish',
		'Inglés'=>'English',
		'Modo Profesor'=>'Teacher View',
		'Modo Alumno'=>'Student View',
		'Entrar'=>'Log in',
		'¿Desea cerrar la sesión?'=>'Are you sure?',
		'NO'=>'NO',
		'SI'=>'YES',
		'Iniciar Sesión'=>'Sign in',
		'Correo Electrónico'=>'Email',
		'Contraseña'=>'Password',
		'¿Has olvidado la contraseña?'=>'Forgot password?',
		'Regístrate'=>'Sign up',
		'Registro de usuario'=>'User Sign up',
		'Nombre'=>'Name',
		'Apellidos'=>'Last name',
		'Nombre de usuario'=>'Username',
		'Rol'=>'Role',
		'Alumno'=>'Student',
		'Profesor'=>'Teacher',
		'Permito a otros profesores usar las tablas creadas por mí'=>'I allow to other teachers to use the tables created by me',
		'Cancelar'=>'Cancel',
		'Crear Cuenta'=>'Create Account',
		'Salir'=>'Log out',

		//Index
		'Anterior' => 'Previous',
		'Siguiente' => 'Next',
		'Ejemplo uno' => 'Example headline',
		'Ejemplo dos' => 'Another example headline',

		//Menu lateral
		'Hojas de Ejercicios' => 'Worksheets',
		'Hoja de Ejercicios' => 'Worksheet',
		'Crear Hoja'=>'Create Worksheet',
		'Editar Hoja'=>'Edit Worksheet',
		'Listar Hojas'=>'Show Worksheets',
		'Ejercicios'=>'Exersices',
		'Ejercicio'=>'Exercise',
		'Crear Ejercicio'=>'Create Exercise',
		'Editar Ejercicio'=>'Edit Exercise',
		'Listar Ejercicios'=>'Show Exersices',
		'Insertar Datos BBDD'=>'Add Data to DB',
		'Añadir Datos'=>'Add Data',
		'Mostrar tablas'=>'',
		'Estadísticas'=>'Statistics',
		'Configuración'=>'Settings',
		'Perfil'=>'Profile',

		//adm profesor -> configuracion
		'Perfil de usuario'=>'User profile',
		'Editar'=>'Change',
		'Guardar cambios'=>'Save changes',
		'Autorizo'=>'Allow',

		//adm profesor -> ejercicios
		'Insertar las tablas sobre las que ejecutar la consulta, la categoría, el nivel del ejercicio, una descripción que sirva de ayuda al alumno, un enunciado y la solución. Si se va a utilizar más de una tabla, asegúsese de que están relacionadas.'=>'Input the used tables, the category, the level, a description for the student, the statement and the solution. If you are going to use more than one table, please check the tables first.',
		'Tablas usadas'=>'Used tables',
		'Categoría'=>'Category',
		'Nivel'=>'Level',
		'Principiante'=>'Basic',
		'Intermedio'=>'Medium',
		'Avanzado'=>'Advanced',
		'Habilitado'=>'Enabled',
		'Deshabilitado'=>'Disabled',
		'Descripcion'=>'Description',
		'Descripcion breve aquí...'=>'Description here...',
		'Enunciado'=>'Statement',
		'Escribe el enunciado aquí...'=>'Write the statement here...',
		'Tablas'=>'Tables',
		'Solución'=>'Solution',
		'Escribe la solución aquí...'=>'Write the solution here...',
		'Visualizar resultado'=>'View the results',
		'Crear ejercicio'=>'Create exercice',
		'Editar Ejercicio'=>'Edit exercice',
		'Podrás editar algunos campos del ejercicio'=>'You can edit some data of the exercises',
		'Búsqueda Avanzada'=>'Advanced search',
		'Realiza una búsqueda detalla por campos'=>'Do a search for fields',
		'Buscar'=>'Search',
		'Limpiar filtros'=>'Clear filters',
		'Podrás editar y eliminar un ejercicio de la lista, además podrás filtar por el/los campo/s que quieras'=>'You will be able to edit and to erase an exercise of the list, also you will be able to filter for the fields that you want',
		'Filtrar'=>'Filter',

		////adm profesor -> tablas
		'Introduzca el código para crear las tablas e introducir los datos. Sólo se permiten las sentencias CREATE TABLE e INSERT INTO.'=>'Introduce the code to create the tables and to insert the information. Only the CREATE TABLE and INSERT INTO statements are allowed.',
		'Inserte el código aquí'=>'Insert the code here',
		'CREATE TABLE coches...'=>'CREATE TABLE cars...',
		'Seleccione un fichero con el código para crear las tablas e introducir en ellas los datos.'=>'Select a file with the code to create the tables and to introduce in them the information.',
		'Seleccionar archivo'=>'Select file',
		'Examinar...'=>'Upload...',
		'Adjuntar'=>'Send',
		'Guardar'=>'Save',
		'Revise el código e inténtelo de nuevo.'=>'Check the code and try it again.',
		''=>'',
		''=>'',
		''=>'',
		''=>'',
		''=>'',
		''=>'',
		''=>'',
		''=>'',




	);

?>